/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mastermind;

/**
 *
 * @author amora
 */
public class prueba2 extends javax.swing.JFrame {

	/**
	 * Creates new form prueba2
	 */
	public prueba2() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_partida = new javax.swing.JPanel();
        jLabel_lista_partidas_usuario = new javax.swing.JLabel();
        jLabel_versus = new javax.swing.JLabel();
        jLabel_lista_partidas_rival = new javax.swing.JLabel();
        jLabel_numero_de_rondas = new javax.swing.JLabel();
        jLabel_rondas = new javax.swing.JLabel();
        jLabel_puntos_rival = new javax.swing.JLabel();
        victoria_usuario = new javax.swing.JLabel();
        jLabel_puntos_usuario = new javax.swing.JLabel();
        jLabel_fecha = new javax.swing.JLabel();
        victoria_rival = new javax.swing.JLabel();

        jPanel_partida.setBackground(new java.awt.Color(243, 230, 0));
        jPanel_partida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_partida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_partidaMouseClicked(evt);
            }
        });

        jLabel_lista_partidas_usuario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_lista_partidas_usuario.setForeground(new java.awt.Color(60, 63, 65));
        jLabel_lista_partidas_usuario.setText("Pepe");

        jLabel_versus.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_versus.setForeground(new java.awt.Color(60, 63, 65));
        jLabel_versus.setText("VS");

        jLabel_lista_partidas_rival.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_lista_partidas_rival.setForeground(new java.awt.Color(60, 63, 65));
        jLabel_lista_partidas_rival.setText("Juan");

        jLabel_numero_de_rondas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_numero_de_rondas.setForeground(new java.awt.Color(60, 63, 65));
        jLabel_numero_de_rondas.setText("Número de rondas:");

        jLabel_rondas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_rondas.setForeground(new java.awt.Color(60, 63, 65));
        jLabel_rondas.setText("3");

        jLabel_puntos_rival.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_puntos_rival.setForeground(new java.awt.Color(60, 63, 65));
        jLabel_puntos_rival.setText("10");

        victoria_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icon/baseline_star_black_18dp.png"))); // NOI18N

        jLabel_puntos_usuario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_puntos_usuario.setForeground(new java.awt.Color(60, 63, 65));
        jLabel_puntos_usuario.setText("18");

        jLabel_fecha.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_fecha.setForeground(new java.awt.Color(60, 63, 65));
        jLabel_fecha.setText("20/01/21");

        victoria_rival.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icon/baseline_star_black_18dp.png"))); // NOI18N

        javax.swing.GroupLayout jPanel_partidaLayout = new javax.swing.GroupLayout(jPanel_partida);
        jPanel_partida.setLayout(jPanel_partidaLayout);
        jPanel_partidaLayout.setHorizontalGroup(
            jPanel_partidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_partidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_partidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_partidaLayout.createSequentialGroup()
                        .addComponent(victoria_usuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_partidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_puntos_usuario)
                            .addComponent(jLabel_lista_partidas_usuario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_versus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_partidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_partidaLayout.createSequentialGroup()
                                .addComponent(jLabel_puntos_rival)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel_partidaLayout.createSequentialGroup()
                                .addComponent(jLabel_lista_partidas_rival)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(victoria_rival)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                                .addComponent(jLabel_fecha))))
                    .addGroup(jPanel_partidaLayout.createSequentialGroup()
                        .addComponent(jLabel_numero_de_rondas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_rondas)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel_partidaLayout.setVerticalGroup(
            jPanel_partidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_partidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_partidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(victoria_usuario)
                    .addGroup(jPanel_partidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_lista_partidas_usuario)
                        .addComponent(jLabel_versus)
                        .addComponent(jLabel_lista_partidas_rival))
                    .addComponent(jLabel_fecha)
                    .addComponent(victoria_rival))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_partidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_puntos_usuario)
                    .addComponent(jLabel_puntos_rival))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_partidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_numero_de_rondas)
                    .addComponent(jLabel_rondas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel_partidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_partidaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel_partidaMouseClicked

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(prueba2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(prueba2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(prueba2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(prueba2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new prueba2().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_fecha;
    private javax.swing.JLabel jLabel_lista_partidas_rival;
    private javax.swing.JLabel jLabel_lista_partidas_usuario;
    private javax.swing.JLabel jLabel_numero_de_rondas;
    private javax.swing.JLabel jLabel_puntos_rival;
    private javax.swing.JLabel jLabel_puntos_usuario;
    private javax.swing.JLabel jLabel_rondas;
    private javax.swing.JLabel jLabel_versus;
    private javax.swing.JPanel jPanel_partida;
    private javax.swing.JLabel victoria_rival;
    private javax.swing.JLabel victoria_usuario;
    // End of variables declaration//GEN-END:variables
}
